#!/usr/bin/env bash

set -e
# check that the debugger folder is present
# in # check that the debugger folder is present
# in XDG_DATA_HOME

if [ ! -e "$XDG_DATA_HOME/debuggers" ]; then
	echo "debugger folder not present"
	echo "creating debugger folder"
	mkdir -p "$XDG_DATA_HOME/debuggers"
	echo "created directory $XDG_DATA_HOME/debuggers/"
fi

git clone https://github.com/microsoft/vscode-node-debug2.git "$XDG_DATA_HOME/debuggers/vscode-node-debug2"

cd "$XDG_DATA_HOME/debuggers/vscode-node-debug2/" || exit
npm install
npm install
NODE_OPTIONS=--no-experimental-fetch npm run build


git clone https://github.com/Microsoft/vscode-chrome-debug "$XDG_DATA_HOME/debuggers/vscode-chrome-debug"
cd "$XDG_DATA_HOME/debuggers/vscode-chrome-debug" || exit
npm install
npm run build

