return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "dockerfile",
      "gitcommit",
      "go",
      "gomod",
      "java",
      "kotlin",
      "lua",
      "markdown",
      "ninja",
      "python",
      "query",
      "rst",
      "rust",
      "sql",
      "terraform",
      "toml",
      "tsx",
      "typescript",
      "yaml",
    },
  },
}
